### ISSUE TITLE
Can't get it to work...

### ISSUE THREAD

**Issue by tybenz** [gosquared/twitter-oauth#4]
Not sure what's happening, or even what my problem is. But I've got a twitter app configured, and my site pushed to heroku. But I keep getting `Error getting OAuth request token`.

Looking at your examples, I have 2 questions that come to mind:
1. Which "callback" setting needs to line up with the Twitter Callback URL? (completeCallback or loginCallback)
2. What [secret key](https://github.com/gosquared/twitter-oauth/blob/master/examples/search.js#L28) do I need to have in the express session cookie? (Not included in README)

**Comment by simontabor** [comment]
Closing as we have https://github.com/gosquared/flutter and this is deprecated
